# Generated by Django 3.0.2 on 2020-01-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='list',
        ),
        migrations.DeleteModel(
            name='UserList',
        ),
    ]
