# Generated by Django 3.0.2 on 2020-01-10 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_auto_20200109_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='text',
        ),
        migrations.AddField(
            model_name='todo',
            name='activity',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_title', models.CharField(default='list title', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todolist.TodoList'),
            preserve_default=False,
        ),
    ]
