# Generated by Django 3.0.2 on 2020-01-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200110_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='activity',
            new_name='todo_text',
        ),
    ]
