# Generated by Django 3.0.2 on 2020-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20200110_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='list_title',
            field=models.CharField(default='list title', max_length=25),
        ),
    ]
