# Generated by Django 3.0.2 on 2020-01-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20200113_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='undone_todos',
            field=models.BooleanField(default=False),
        ),
    ]
